main: com.kryeit.CreativeStuff
version: 1.1
author: MuriPlz
api-version: 1.18
depend: [AFKPlus,GriefDefender]
name: Stuff
commands:
  online:
    description: online players
    permission: stuff.online
  discord:
    description: sends discord link
  forum:
    description: sends forum link
  rules:
    description: sends rules link
  sendcoords:
    description: sends your cords to the player
    aliases:
      - sharecoords
  patreon:
    description: sends patreon link
    aliases:
      - donate
  timeplayed:
    description: shows time played
  lastonline:
    description: shows last time online
  mute:
    description: mutes players
    permission: stuff.mute
  invsee:
    description: gets a player inventory
    permission: stuff.invsee
  enderinvsee:
    description: gets a player enderchest
    permission: stuff.enderinvsee
  kill:
    description: kills a player
  survival:
    description: sends you to survival
  creative:
    description: sends you to creative
  sch:
    description: gives you the schematic tools
  fly:
    description: makes you fly
  claimkit:
    description: gives you the claim kit